spring.application.name=eyewear_management_backend

#Datasource Config
spring.datasource.url=jdbc:sqlserver://database.purintech.id.vn:1433;databaseName=EyewearManagement;encrypt=true;trustServerCertificate=true
spring.datasource.username=eyewear
spring.datasource.password=eyewear
#JPA Config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.signerKey=56235e27daf8f8e68ce33febf5400cf93dbd5f6ec40a14531754168ea0d32486

cloudinary.cloud-name=dbgkfgkrl
cloudinary.api-key=349146117748721
cloudinary.api-secret=dW4_Qy27QgUd63_ihqd1iI1173M