spring:
  application:
    name: eyewear_management_backend

  datasource:
    url: jdbc:sqlserver://database.purintech.id.vn:1433;databaseName=EyewearManagement;encrypt=true;trustServerCertificate=true
    username: eyewear
    password: eyewear
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

jwt:
  signerKey: 56235e27daf8f8e68ce33febf5400cf93dbd5f6ec40a14531754168ea0d32486
  valid-duration: 3600
  refreshable-duration: 36000

ghn:
  base-url: https://online-gateway.ghn.vn/shiip/public-api
  token: ${GHN_TOKEN:2180ff60-11e5-11f1-bb99-4a6bb163b6a3}
  shop-id: ${GHN_SHOP_ID:4883785}
  from-district-id: ${GHN_FROM_DISTRICT_ID:1451}
  from-ward-code: ${GHN_FROM_WARD_CODE:20904}
  preferred-service-type-id: 2

  # === Package defaults for eyewear ===
  pkg:
    length: 20   # cm
    width: 15    # cm
    height: 8    # cm

    weight:
      contact-lens: 120        # gram
      lens: 220                # gram
      frame: 300               # gram
      prescription: 450        # gram (frame + lens)
      def: 250             # gram fallback

cloudinary:
  cloud-name: dbgkfgkrl
  api-key: 349146117748721
  api-secret: dW4_Qy27QgUd63_ihqd1iI1173M


vnpay:
  pay-url: ${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  tmn-code: ${VNPAY_TMN_CODE:WG7VHCKH}
  hash-secret: ${VNPAY_HASH_SECRET:VC9SQMAEOGZYH3KZSCT6WPDLO7CFP2DU}
  return-url: ${VNPAY_RETURN_URL:http://localhost:8080/payments/vnpay/return}
  ipn-url: ${VNPAY_IPN_URL:http://localhost:8080/payments/vnpay/ipn}
  version: "2.1.0"
  command: "pay"
  curr-code: "VND"
  locale: "vn"
  order-type: "other"
  expire-minutes: 15

app:
  cors:
    allowed-origin-patterns:
      - "http://localhost:5173"
      - "http://localhost:5174"
      - "http://localhost:5175"
      - "https://api-eyewear.purintech.id.vn"
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:5173}
    success-path: /success
    cancel-path: /cancel
    fail-path: /payment-result

payos:
  client-id: 6cad7040-fb24-4701-8ab0-7c2313c13f4e
  api-key: 4f3f8b40-0afb-4ffc-8a7d-c74dea4230af
  checksum-key: db796b0590d5779b8b5bac09a915fe58a533c9f24d1c3057b0c16f334b2a44c6

